import { Component, OnInit } from "@angular/core";
import * as moment from "moment";
import { StoreService } from "./../../lib/store.service";
import { Observable } from "rxjs/Observable";

@Component({
  selector: "cf-home",
  template: `
    <main>
      <h3>ng5 Cash-flow</h3>

      <ng-content *ngIf="userIsAnonymous$ | async; else logged"></ng-content>
      <ng-template #logged><h5>You are logged in.</h5></ng-template>

      <p>Small Angular5 app, using all of new main features that Angular2 is bringing to us.
        Additionally using the slight csss library <a href="https://milligram.io">Miligram</a>.</p>
      <p>It simulates a small and simple app to control the cash flow of a house, using an online API in MongoDb.</p>
      <p>Features implemented:</p>
      <ul>
        <li>Pages and routes (SPA)</li>
        <li>Forms, ngModel, tables and data model in Angular</li>
        <li>Data flow between components. Dependency injections</li>
        <li>Inyectable services and service as provider</li>
        <li>Http communications and http interceptors</li>
        <li>Security and user validation with JWT</li>
        <li>Observables and RxJS</li>
      </ul>
      <p><small><i>Project generated by <a href="https://github.com/angular/angular-cli">Angular ClI</a></i></small></p>
      <blockquote>Today: {{ now }} <br> Tomorrow: {{ tomorrow }}</blockquote>
    </main>`,
  styles: []
})
export class HomeComponent implements OnInit {

  now = moment().format();
  tomorrow = moment()
    .add(1, "days")
    .format();

  public userIsAnonymous$: Observable<boolean>;

  constructor(private store: StoreService) {}

  ngOnInit() {
    this.userIsAnonymous$ = this.store.getUserIsAnonymous$();
  }

}
